# -*- coding: utf-8 -*-
"""Jonathan Rius- Homework Assignment #2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7t_9_kMJjl592T0yJOzadrjCAkUwehs

Jonathan Rius: Assignment #2
1. Prompts a user to enter 10 integers.

2. If the user enters anything other than integers, remind her that only integers are allowed and let her retry.

3. Don't allow the user to enter more than 10 or less than 10 integers.

4. Display the 10 integers back to the user at the end. Calculate the following statistics from the 10 integers entered *Minimum Maximum Range Mean Variance Standard Deviation*

#I began the assignment by chunking the assignment into four parts; prompting the user, reminding the user, not allowing the user and calculation.

**Revised** Prompt For User
"""

num_list = []

while len(num_list) < 10:  

    num = input(f"\nplease enter an integer ({len(num_list) + 1} of 10): ")

    try:
        num = int(num)
        num_list.append(num)
    except:
        print("\nYou have entered a non-integer. Please enter an integer.")

print("\n", num_list)

# There are several things going on here, first prompting the user to input ten numbers is easy enough, but one needs to stop the user if he/she is inputting non-integers and only count integers towards the total ten integers.
# The input adds to the total of 10 integers, the len num list code is to ensure the user doesn't go past 10 integers, and the except code is the reminder to make the user sticks to integers.

"""**Calculate** average,min, max, range"""

total = 0
for num in num_list:
    total += num

print(f"Average = {total/len(num_list)}" )
print(f"Minimum is:", min(num_list))
print(f"Maximum is:", max(num_list))
print(f"Range is" ,(max(num_list))- min(num_list))

# Average is total divided by lens which refers to amount of numbers in list, I just used min and max functions for min and max but applied to the num_list so the list above was being referred to. Range is simply max minus min.

"""**Caculate** Variance and Standard Deviation"""

def mean(num_list):
    
    total = 0  

    for num in num_list:
        total += num

    return total / len(num_list)


def var(num_list):
    
    the_mean = mean(num_list)                     
    
    squared_diff = [(x - the_mean) ** 2 for x in num_list]    
    
    return mean(squared_diff)                   

import math

def std(num_list):
    the_var = var(num_list)
    return math.sqrt(the_var)


the_std = std(num_list)

print("std = ", round(the_std,2))
print("var = ",round(the_std,2)**2)

# First mean needs to be defined as it is the basis for the variance function 
# Then once the variance function is defined with the addition of the mean being defined, one can take the square root of the variance function by importing math. This gives you standard deviation. 
# After I apply a square power on the standard deviation to obtain the variance